FROM node:10-alpine

RUN apk update \
    && apk upgrade \
    && apk add --no-cache --update \
    git \
    bash \
    python \
    python-dev \
    py-pip \
    build-base

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN npm install --ci 

COPY . /usr/src/app

CMD ["tail", "-f", "/dev/null"]