on:
  pull_request:
    types: [opened, reopened, synchronize]

name: "Pull Requests"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  linters:
    name: Linters
    uses: ./.github/workflows/linters.yml

  release-check:
    name: Release Check
    uses: ./.github/workflows/publish.yml
